create extension if not exists pgcrypto;
create type public.user_role as enum ('user','admin');
create type public.profile_status as enum ('active','hidden');
create type public.moderation_status as enum ('pending','approved','rejected','changes_requested');
create type public.report_status as enum ('pending','reviewed','dismissed');
create type public.claim_status as enum ('pending','approved','rejected');
create table public.user_profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null,email text not null,username text unique not null,role public.user_role not null default 'user',created_at timestamptz not null default now());
create table public.person_profiles(id uuid primary key default gen_random_uuid(),display_name text not null,search_name text generated always as(lower(display_name)) stored,username text unique,created_at timestamptz not null default now(),claimed boolean not null default false,status public.profile_status not null default 'active');
create table public.experiences(id uuid primary key default gen_random_uuid(),target_profile_id uuid not null references public.person_profiles(id) on delete cascade,author_id uuid not null references public.user_profiles(id) on delete cascade,relationship_type text not null check(relationship_type in('Dating','Former partner','Long-term partner','Short-term relationship','Situationship','Other')),relationship_duration text not null check(relationship_duration in('Less than 3 months','3–6 months','6–12 months','1–2 years','2+ years')),communication_score int not null check(communication_score between 1 and 5),commitment_score int not null check(commitment_score between 1 and 5),boundaries_score int not null check(boundaries_score between 1 and 5),lifestyle_score int not null check(lifestyle_score between 1 and 5),values_score int not null check(values_score between 1 and 5),written_experience text not null check(char_length(written_experience) between 20 and 5000),moderation_status public.moderation_status not null default 'pending',created_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),experience_id uuid not null references public.experiences(id) on delete cascade,reporter_id uuid not null references public.user_profiles(id) on delete cascade,reason text not null,description text,status public.report_status not null default 'pending',created_at timestamptz not null default now());
create table public.profile_claims(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.person_profiles(id) on delete cascade,claimant_id uuid not null references public.user_profiles(id) on delete cascade,reason text not null,status public.claim_status not null default 'pending',created_at timestamptz not null default now());
create table public.moderation_actions(id uuid primary key default gen_random_uuid(),experience_id uuid not null references public.experiences(id) on delete cascade,admin_id uuid not null references public.user_profiles(id) on delete cascade,action text not null,notes text,created_at timestamptz not null default now());
create index experiences_target_idx on public.experiences(target_profile_id,moderation_status,created_at desc);
create index experiences_author_idx on public.experiences(author_id,created_at desc);
create index reports_status_idx on public.reports(status,created_at desc);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.user_profiles(id,name,email,username) values(new.id,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1)),new.email,lower(coalesce(new.raw_user_meta_data->>'username','user_'||substr(new.id::text,1,8)))) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_profiles where id=auth.uid() and role='admin'); $$;
alter table public.user_profiles enable row level security;alter table public.person_profiles enable row level security;alter table public.experiences enable row level security;alter table public.reports enable row level security;alter table public.profile_claims enable row level security;alter table public.moderation_actions enable row level security;
create policy "own user profile read" on public.user_profiles for select using(id=auth.uid() or public.is_admin());
create policy "own user profile update" on public.user_profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "active profiles public read" on public.person_profiles for select using(status='active');
create policy "authenticated create profiles" on public.person_profiles for insert to authenticated with check(status='active');
create policy "admins manage profiles" on public.person_profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "approved experiences public read" on public.experiences for select using(moderation_status='approved');
create policy "authors read own experiences" on public.experiences for select to authenticated using(author_id=auth.uid() or public.is_admin());
create policy "users submit pending experiences" on public.experiences for insert to authenticated with check(author_id=auth.uid() and moderation_status='pending');
create policy "admins moderate experiences" on public.experiences for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admins delete experiences" on public.experiences for delete to authenticated using(public.is_admin());
create policy "users create reports" on public.reports for insert to authenticated with check(reporter_id=auth.uid());
create policy "users read own reports" on public.reports for select to authenticated using(reporter_id=auth.uid() or public.is_admin());
create policy "admins update reports" on public.reports for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "users create claims" on public.profile_claims for insert to authenticated with check(claimant_id=auth.uid());
create policy "users read own claims" on public.profile_claims for select to authenticated using(claimant_id=auth.uid() or public.is_admin());
create policy "admins update claims" on public.profile_claims for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admins read moderation log" on public.moderation_actions for select to authenticated using(public.is_admin());
create policy "admins write moderation log" on public.moderation_actions for insert to authenticated with check(public.is_admin());
